---
title: "OmicAnalyzer API"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{OmicAnalyzer API}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  comment = "#>"
)
```

```{r packages}
library(jsonlite)
library(OmicAnalyzer)
```

```{r test-data, include=FALSE}
tmplib <- tempfile()
dir.create(tmplib)
.libPaths(c(tmplib, .libPaths()))
OmicAnalyzer::installStudy(OmicAnalyzer:::testStudy(name = "ABC"))
OmicAnalyzer::installStudy(OmicAnalyzer:::testStudy(name = "XYZ"))
```

## List studies

```{r list-studies, eval=FALSE}
studies <- getInstalledStudies()
```

```{r list-studies-hidden, echo=FALSE}
studies <- listStudies(libraries = tmplib)
```

```{r list-studies-json}
toJSON(studies, pretty = TRUE)
```

## Installed studies

```{r studies, eval=FALSE}
(studies <- getInstalledStudies())
```

```{r studies-hidden, echo=FALSE}
(studies <- getInstalledStudies(libraries = tmplib))
```

```{r studies-json}
toJSON(studies, pretty = TRUE)
```

## Models

```{r models}
(models <- getModels("ABC"))
toJSON(models, pretty = TRUE)
```

## Tests

```{r tests}
(tests <- getTests("ABC", "model_01"))
toJSON(tests, pretty = TRUE)
```

## Results

```{r results}
result <- getResults("ABC", "model_01", "test_01")
head(result)
toJSON(result[1:2, ], pretty = TRUE)
```

## Results table

```{r results-table}
resultsTable <- getResultsTable("ABC", "model_01", "test_01")
head(resultsTable)
toJSON(resultsTable[1:2, ], pretty = TRUE)
```

## Enrichments

```{r enrichments}
enrichment <- getEnrichments("ABC", "model_01", "test_01", "annotation_01")
head(enrichment)
toJSON(enrichment[1:2, ], pretty = TRUE)
```

## Enrichments table

```{r enrichments-table}
enrichmentsTable <- getEnrichmentsTable("ABC", "model_01", "annotation_01")
head(enrichmentsTable)
toJSON(enrichmentsTable[1:2, ], pretty = TRUE)
```

```{r enrichments-table-adjusted}
enrichmentsTable <- getEnrichmentsTable("ABC", "model_01", "annotation_01", type = "adjusted")
head(enrichmentsTable)
toJSON(enrichmentsTable[1:2, ], pretty = TRUE)
```

## Enrichments network

```{r enrichments-network}
enrichmentsNetwork <- getEnrichmentsNetwork("ABC", "model_01", "annotation_01")
head(enrichmentsNetwork)
toJSON(enrichmentsNetwork, pretty = TRUE)
```
