<!--
%\VignetteIndexEntry{OmicAnalyzer get() functions}
%\VignetteEngine{knitr::knitr}
%\VignetteEncoding{UTF-8}
-->

# OmicAnalyzer get() functions

**Date:** `r Sys.Date()`

**Package version:** `r packageVersion("OmicAnalyzer")`

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  comment = "#>"
)
```

```{r packages}
library(jsonlite)
library(OmicAnalyzer)
```

```{r test-data, include=FALSE}
tmplib <- tempfile()
dir.create(tmplib)
.libPaths(c(tmplib, .libPaths()))
OmicAnalyzer::installStudy(OmicAnalyzer:::testStudy(name = "ABC"))
OmicAnalyzer::installStudy(OmicAnalyzer:::testStudy(name = "XYZ"))
```

## Installed studies

```{r studies, eval=FALSE}
(studies <- getInstalledStudies())
```

```{r studies-hidden, echo=FALSE}
(studies <- getInstalledStudies(libraries = tmplib))
```

```{r studies-json}
toJSON(studies, pretty = TRUE)
```

## Models

```{r models}
(models <- getModels("ABC"))
toJSON(models, pretty = TRUE)
```

## Tests

```{r tests}
(tests <- getTests("ABC", "model_01"))
toJSON(tests, pretty = TRUE)
```

## Annotations

```{r annotations}
(annotations <- getAnnotations("ABC", "annotation_01"))
toJSON(annotations, pretty = TRUE)
```

## Results

```{r results}
result <- getResults("ABC", "model_01", "test_01")
head(result)
toJSON(result[1:2, ], pretty = TRUE)
```

## Enrichments

```{r enrichments}
enrichment <- getEnrichments("ABC", "model_01", "annotation_01", "test_01")
head(enrichment)
toJSON(enrichment[1:2, ], pretty = TRUE)
```

