name: Quick test

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-18.04

    env:
      R_LIBS_USER: ~/rlibs
      R_COMPILE_AND_INSTALL_PACKAGES: never

    steps:
    - uses: actions/checkout@v2
    - name: Install system dependencies
      run: |
        export DEBIAN_FRONTEND=noninteractive
        sudo apt-get update
        sudo apt-get install --yes --no-install-recommends \
          libcurl4-openssl-dev \
          libssl-dev \
          libprotobuf-dev \
          protobuf-compiler \
          libxml2-dev
    - name: Cache R packages
      uses: actions/cache@v2
      with:
        path: ${{ env.R_LIBS_USER }}
        key: ${{ runner.os }}-packages
    - name: Install R
      run: |
        sudo apt-get install --yes --no-install-recommends \
          r-base \
          r-base-dev
        # Create user library directory
        mkdir -p ${{ env.R_LIBS_USER }}
        echo 'R_LIBS_USER=${{ env.R_LIBS_USER }}' > $HOME/.Renviron
    - name: Install R packages
      run: |
        # Use RSPM to install package binaries
        options(HTTPUserAgent = sprintf("R/%s R (%s)", getRversion(), paste(getRversion(), R.version$platform, R.version$arch, R.version$os)))
        options(repos = c(CRAN = "https://packagemanager.rstudio.com/cran/__linux__/bionic/latest"))

        install.packages("remotes")
        remotes::install_deps(dependencies = TRUE)
      shell: sudo Rscript {0}
    - name: Session information
      run: sessionInfo()
      shell: Rscript {0}
    - name: Build and install
      run: |
        R CMD build --no-manual --no-build-vignettes .
        R CMD INSTALL --no-docs --no-multiarch --no-staged-install OmicNavigator_*.tar.gz
    - name: Test
      run: tinytest::test_package("OmicNavigator")
      shell: Rscript {0}
    - name: Run vignettes
      run: |
        vignettes <- Sys.glob("vignettes/*.Rnw")
        tangled <- sub("nw$", "", basename(vignettes))
        for (i in seq_along(vignettes)) {
          utils::Stangle(vignettes[i])
          source(tangled[i], local = new.env())
        }
      shell: Rscript {0}
